### ISSUE TITLE
FromStr Err type don't implement  std::error::Error trait

### ISSUE THREAD

**Issue by Mart-Bogdan** [SergioBenitez/ubyte#1]
Err of FromStr is defined as Option<(usize,char)> and it's not possible to handle it with generic error handling code.

I've encountered a problem when tried to use your crate in conjunction with `structopt`.

**Comment by Mart-Bogdan** [comment]
actually it fails with

`no method named `to_string` found for enum `std::option::Option<(usize, char)>` in the current scope`

```
pub enum Option<T> {
    | ------------------
    | |
    | doesn't satisfy `_: std::fmt::Display`
    | doesn't satisfy `_: std::string::ToString`
    = note: the method `to_string` exists but the following trait bounds were not satisfied:
            `std::option::Option<(usize, char)>: std::fmt::Display`
            which is required by `std::option::Option<(usize, char)>: std::string::ToString`
```

**Comment by SergioBenitez** [comment]
Ah, indeed, this is suboptimal. I've completed a fix and will push soon, followed by a release as `0.10`. Thank you for posting an issue!
