### ISSUE TITLE
How to add space between the number and the unit?

### ISSUE THREAD

**Issue by pkolaczk** [SergioBenitez/ubyte#9]
The linguistically correct way of formatting values with units (at least in English and in Polish) is to put a space between the number and the unit: "2 MB" not "2MB". Is there an option to do this?

**Comment by SergioBenitez** [comment]
Yes. Use [`repr()`](https://docs.rs/ubyte/latest/ubyte/struct.ByteUnit.html#method.repr) and format it however you'd like. See the existing `Display` implementation for inspiration.
